import sqlite3
import uuid
from datetime import datetime, timezone
import json
import httpx
import os
import re
import logging
from pydantic import BaseModel
from typing import List, Optional

from utils.recall import recall_data
from tool.Issues import open_github_issue
from tool.pages import create_notion_page
from tool.fetch_issue import fetch_github_issue
from tool.fetch_pr import fetch_github_pr
from tool.fetch_diff import fetch_github_diff
from tool.fetch_contributor import (
    fetch_all_contributors,
    fetch_contributor_profile,
    format_contributors_list,
)

logger = logging.getLogger(__name__)

class ConversationResponse(BaseModel):
    id: str
    title: str
    created_at: str

class MessageResponse(BaseModel):
    id: str
    role: str
    content: str
    created_at: str

class SendMessageRequest(BaseModel):
    message: str

def handle_list_conversations(project_id: str, db: sqlite3.Connection) -> List[ConversationResponse]:
    cursor = db.cursor()
    cursor.execute("SELECT id, title, created_at FROM conversations WHERE project_id = ? ORDER BY created_at DESC", (project_id,))
    rows = cursor.fetchall()
    return [ConversationResponse(id=r["id"], title=r["title"] or "New Chat", created_at=r["created_at"]) for r in rows]

def handle_create_conversation(project_id: str, db: sqlite3.Connection) -> ConversationResponse:
    cursor = db.cursor()
    conv_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()
    cursor.execute(
        "INSERT INTO conversations (id, project_id, title, created_at) VALUES (?, ?, ?, ?)",
        (conv_id, project_id, "New Chat", now)
    )
    db.commit()
    return ConversationResponse(id=conv_id, title="New Chat", created_at=now)

def handle_get_messages(conversation_id: str, db: sqlite3.Connection) -> List[MessageResponse]:
    cursor = db.cursor()
    cursor.execute("SELECT id, role, content, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at ASC", (conversation_id,))
    rows = cursor.fetchall()
    return [MessageResponse(**dict(r)) for r in rows]

async def _call_llm(messages: list, expect_json: bool = False) -> str:
    api_key = os.getenv("GROQ_API")
    if not api_key:
        raise ValueError("GROQ_API not found in environment variables")
        
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "qwen/qwen3-32b",
        "messages": messages,
        "temperature": 0.2
    }
    if expect_json:
        payload["response_format"] = {"type": "json_object"}
        
    async with httpx.AsyncClient() as client:
        res = await client.post(url, headers=headers, json=payload, timeout=60.0)
        res.raise_for_status()
        data = res.json()
        content = data["choices"][0]["message"]["content"]
        # Remove <think> blocks generated by thinking models
        content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
        return content

async def handle_send_message(conversation_id: str, req: SendMessageRequest, db: sqlite3.Connection) -> MessageResponse:
    cursor = db.cursor()
    
    # Verify conversation exists and get project info
    cursor.execute("""
        SELECT c.project_id, p.dataset, p.repo_owner, p.repo_name 
        FROM conversations c 
        JOIN projects p ON c.project_id = p.id 
        WHERE c.id = ?
    """, (conversation_id,))
    conv_data = cursor.fetchone()
    if not conv_data:
        raise ValueError("Conversation not found")
        
    project_id = conv_data["project_id"]
    dataset = conv_data["dataset"]
    repo_owner = conv_data["repo_owner"]
    repo_name = conv_data["repo_name"]
    
    # Fetch tokens
    cursor.execute("SELECT source_type, token FROM project_sources WHERE project_id = ?", (project_id,))
    tokens = {row["source_type"]: row["token"] for row in cursor.fetchall()}
    
    # Save user message
    now = datetime.now(timezone.utc).isoformat()
    msg_id = str(uuid.uuid4())
    cursor.execute(
        "INSERT INTO messages (id, conversation_id, role, content, created_at) VALUES (?, ?, 'user', ?, ?)",
        (msg_id, conversation_id, req.message, now)
    )
    db.commit()
    
    # Detect tool call
    is_issue = "/issue" in req.message
    is_notion = "/Notion" in req.message
    is_contributors = req.message.strip().lower() == "/contributors"

    # Detect iss{N}, pr{N}, diff{N} patterns
    iss_match = re.match(r'^iss(\d+)\b', req.message.strip(), re.IGNORECASE)
    pr_match = re.match(r'^pr(\d+)\b', req.message.strip(), re.IGNORECASE)
    diff_match = re.match(r'^diff(\d+)\b', req.message.strip(), re.IGNORECASE)

    # Detect @username mention (must start with @)
    at_match = re.match(r'^@([\w.-]+)\b', req.message.strip())

    query = req.message.replace("/issue", "").replace("/Notion", "").strip()
    if not query:
        query = req.message
        
    # Early tool validation
    if is_notion and not tokens.get("notion"):
        assistant_reply = "Please add a Notion Integration Token to this project first to use the /Notion tool."
        asst_id = str(uuid.uuid4())
        asst_now = datetime.now(timezone.utc).isoformat()
        cursor.execute(
            "INSERT INTO messages (id, conversation_id, role, content, created_at) VALUES (?, ?, 'assistant', ?, ?)",
            (asst_id, conversation_id, assistant_reply, asst_now)
        )
        db.commit()
        return MessageResponse(id=asst_id, role="assistant", content=assistant_reply, created_at=asst_now)
    # Recall context
    try:
        context = await recall_data(query, datasets=[dataset], top_k=5)
        context_str = "\n".join([str(c) for c in context]) if context else "No additional context found."
    except Exception as e:
        logger.error(f"Failed to fetch context from knowledge graph: {e}")
        context_str = "No additional context found."
    
    # Get conversation history
    cursor.execute("SELECT role, content FROM messages WHERE conversation_id = ? ORDER BY created_at ASC LIMIT 10", (conversation_id,))
    history = cursor.fetchall()
    
    llm_messages = [{"role": "system", "content": f"You are a helpful assistant for the project {repo_owner}/{repo_name}. Context:\n{context_str}"}]
    for h in history[:-1]: # Don't add the last one twice
        llm_messages.append({"role": h["role"], "content": h["content"]})
        
    # Add the current user query to history
    llm_messages.append({"role": "user", "content": req.message})
    
    if is_issue:
        llm_messages[0]["content"] += """
        
You need to open a GitHub issue. Based on the user's request and the context provided, return ONLY a valid JSON object with these exact keys:
"title": The title of the issue
"body": The body/description of the issue
"response_text": A friendly message to display to the user confirming you will open the issue, and summarizing what it contains.
"""
        try:
            llm_response = await _call_llm(llm_messages, expect_json=True)
            data = json.loads(llm_response)
            await open_github_issue(repo_owner, repo_name, data["title"], data["body"], tokens["github"])
            assistant_reply = data.get("response_text", "Issue successfully created.")
        except Exception as e:
            logger.error(f"Failed to process /issue tool: {e}", exc_info=True)
            assistant_reply = f"Sorry, I failed to open the GitHub issue. Error: {e}"
            
    elif is_notion:
        llm_messages[0]["content"] += """
        
You need to create a Notion page. Based on the user's request and the context provided, return ONLY a valid JSON object with these exact keys:
"title": The title of the page
"content": The content of the page (plain text)
"parent_id": The ID of the parent page (infer from context or user message, or use a default placeholder if none provided)
"response_text": A friendly message to display to the user confirming the page creation.
"""
        try:
            llm_response = await _call_llm(llm_messages, expect_json=True)
            data = json.loads(llm_response)
            parent_id = data.get("parent_id") or "default_parent_id"
            await create_notion_page(parent_id, data["title"], data["content"], tokens["notion"])
            assistant_reply = data.get("response_text", "Notion page successfully created.")
        except Exception as e:
            logger.error(f"Failed to process /Notion tool: {e}", exc_info=True)
            assistant_reply = f"Sorry, I failed to create the Notion page. Error: {e}"
            
    elif iss_match:
        issue_num = int(iss_match.group(1))
        follow_up = req.message[iss_match.end():].strip()
        try:
            issue_data = await fetch_github_issue(repo_owner, repo_name, issue_num, tokens["github"])
            if not issue_data.get("exists", True) or issue_data.get("number") is None:
                assistant_reply = f"Issue #{issue_num} does not exist in {repo_owner}/{repo_name}."
            else:
                llm_messages[0]["content"] += f"\n\nThe user is asking about this GitHub issue:\n\n{issue_data['markdown']}"
                if follow_up:
                    llm_messages[-1] = {"role": "user", "content": follow_up}
                else:
                    llm_messages[-1] = {"role": "user", "content": f"Summarize issue #{issue_num} and tell me what it's about, its current status, and any important discussion."}
                assistant_reply = await _call_llm(llm_messages, expect_json=False)
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                assistant_reply = f"Issue #{issue_num} does not exist in {repo_owner}/{repo_name}."
            else:
                logger.error(f"Failed to fetch issue #{issue_num}: {e}", exc_info=True)
                assistant_reply = f"Sorry, I couldn't fetch issue #{issue_num}. Error: {e}"
        except Exception as e:
            logger.error(f"Failed to fetch issue #{issue_num}: {e}", exc_info=True)
            assistant_reply = f"Sorry, I couldn't fetch issue #{issue_num}. Error: {e}"

    elif pr_match:
        pr_num = int(pr_match.group(1))
        follow_up = req.message[pr_match.end():].strip()
        try:
            pr_data = await fetch_github_pr(repo_owner, repo_name, pr_num, tokens["github"])
            if not pr_data.get("exists", True) or pr_data.get("number") is None:
                assistant_reply = f"PR #{pr_num} does not exist in {repo_owner}/{repo_name}."
            else:
                llm_messages[0]["content"] += f"\n\nThe user is asking about this GitHub pull request:\n\n{pr_data['markdown']}"
                if follow_up:
                    llm_messages[-1] = {"role": "user", "content": follow_up}
                else:
                    llm_messages[-1] = {"role": "user", "content": f"Summarize PR #{pr_num}, explain what it changes, its review status, and any important feedback."}
                assistant_reply = await _call_llm(llm_messages, expect_json=False)
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                assistant_reply = f"PR #{pr_num} does not exist in {repo_owner}/{repo_name}."
            else:
                logger.error(f"Failed to fetch PR #{pr_num}: {e}", exc_info=True)
                assistant_reply = f"Sorry, I couldn't fetch PR #{pr_num}. Error: {e}"
        except Exception as e:
            logger.error(f"Failed to fetch PR #{pr_num}: {e}", exc_info=True)
            assistant_reply = f"Sorry, I couldn't fetch PR #{pr_num}. Error: {e}"

    elif diff_match:
        diff_num = int(diff_match.group(1))
        follow_up = req.message[diff_match.end():].strip()
        try:
            diff_data = await fetch_github_diff(repo_owner, repo_name, diff_num, tokens["github"])
            if not diff_data.get("exists", True):
                assistant_reply = f"PR #{diff_num} does not exist in {repo_owner}/{repo_name}."
            else:
                llm_messages[0]["content"] += f"\n\nThe user is asking about the code diff of this GitHub pull request:\n\n{diff_data['diff_markdown']}"
                if follow_up:
                    llm_messages[-1] = {"role": "user", "content": follow_up}
                else:
                    llm_messages[-1] = {"role": "user", "content": f"Summarize the code changes in PR #{diff_num}. Explain what each file change does, the overall intent of the PR, and any potential issues you spot."}
                assistant_reply = await _call_llm(llm_messages, expect_json=False)
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                assistant_reply = f"PR #{diff_num} does not exist in {repo_owner}/{repo_name}."
            else:
                logger.error(f"Failed to fetch diff for PR #{diff_num}: {e}", exc_info=True)
                assistant_reply = f"Sorry, I couldn't fetch the diff for PR #{diff_num}. Error: {e}"
        except Exception as e:
            logger.error(f"Failed to fetch diff for PR #{diff_num}: {e}", exc_info=True)
            assistant_reply = f"Sorry, I couldn't fetch the diff for PR #{diff_num}. Error: {e}"

    elif is_contributors:
        # List all contributors for this repo
        try:
            contributors = await fetch_all_contributors(repo_owner, repo_name, tokens["github"])
            assistant_reply = format_contributors_list(contributors, repo_owner, repo_name)
        except Exception as e:
            logger.error(f"Failed to fetch contributors: {e}", exc_info=True)
            assistant_reply = f"Sorry, I couldn't fetch contributors for {repo_owner}/{repo_name}. Error: {e}"

    elif at_match:
        # @username — fetch profile and answer question or summarise
        username = at_match.group(1)
        follow_up = req.message[at_match.end():].strip()
        try:
            profile = await fetch_contributor_profile(repo_owner, repo_name, username, tokens["github"])
            if not profile.get("exists"):
                reason = profile.get("reason", "")
                if reason == "user_not_found":
                    assistant_reply = f"GitHub user @{username} does not exist."
                else:
                    assistant_reply = f"@{username} has no recorded activity (commits, PRs, or issues) in {repo_owner}/{repo_name}."
            else:
                # Recall KG context for this contributor
                recall_query = f"contributions by {username} {follow_up}".strip()
                try:
                    context = await recall_data(recall_query, datasets=[dataset], top_k=5)
                    extra_ctx = "\n".join([str(c) for c in context]) if context else ""
                except Exception:
                    extra_ctx = ""

                system_extra = f"\n\nHere is the contributor's GitHub profile and activity in {repo_owner}/{repo_name}:\n\n{profile['markdown']}"
                if extra_ctx:
                    system_extra += f"\n\nAdditional context from the project knowledge graph:\n{extra_ctx}"
                llm_messages[0]["content"] += system_extra

                if follow_up:
                    llm_messages[-1] = {"role": "user", "content": follow_up}
                else:
                    llm_messages[-1] = {
                        "role": "user",
                        "content": f"Give a detailed summary of @{username}'s contributions to {repo_owner}/{repo_name}. Cover what they've worked on, the impact of their PRs, and any notable patterns in their issues.",
                    }
                assistant_reply = await _call_llm(llm_messages, expect_json=False)
        except Exception as e:
            logger.error(f"Failed to fetch contributor @{username}: {e}", exc_info=True)
            assistant_reply = f"Sorry, I couldn't fetch the profile for @{username}. Error: {e}"

    else:
        # Standard chat
        try:
            assistant_reply = await _call_llm(llm_messages, expect_json=False)
        except Exception as e:
            logger.error(f"Failed to call LLM: {e}", exc_info=True)
            assistant_reply = "I'm having trouble connecting to the AI model right now."

    # Save assistant reply
    asst_id = str(uuid.uuid4())
    asst_now = datetime.now(timezone.utc).isoformat()
    cursor.execute(
        "INSERT INTO messages (id, conversation_id, role, content, created_at) VALUES (?, ?, 'assistant', ?, ?)",
        (asst_id, conversation_id, assistant_reply, asst_now)
    )
    
    # Auto-update conversation title if it's the first message
    if len(history) <= 1:
        title = req.message[:50] + "..." if len(req.message) > 50 else req.message
        cursor.execute("UPDATE conversations SET title = ? WHERE id = ?", (title, conversation_id))
        
    db.commit()
    
    return MessageResponse(id=asst_id, role="assistant", content=assistant_reply, created_at=asst_now)
